name: Test upgrade

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cli-version: ['1.2.3', '1.2.2']
        capabilities: ['command-bot', 'tab']
        language: ['javascript', 'typescript']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @microsoft/teamsfx-cli@${{ matrix.cli-version }}
    - run: teamsfx new --capabilities ${{ matrix.capabilities }} --programming-language ${{ matrix.language }} --interactive false
    - run: npm install -g @microsoft/teamsfx-cli@alpha
    - run: teamsfx upgrade --force